### ISSUE TITLE
Remove GPL

### ISSUE THREAD

**Issue by davelab6** [signalwerk/fontstep#2]
The file says its dual licensed - https://github.com/signalwerk/fontstep/blob/master/fontstep.py#L18-L20 - but since BSD-2 is GPL compatible, the GPL licensing is redundant and can be removed to simplify life :)

**Comment by signalwerk** [comment]
Well there are some reasons why two compatible licenses. But since other libs (jQuery as a prominent example; [jQuery Licensing Changes](http://blog.jquery.com/2012/09/10/jquery-licensing-changes/)) also start to move away from dual licensing I agree with you. 

Here we go: bc337bff4a95e949ebd7403f6d89bd61c17fbd53

**Comment by davelab6** [comment]
Thanks!! BTW...

> there are some reasons why two compatible licenses

I can't understand this :)
